#!/bin/sh

pkill sxhkd
sxhkd &

pkill polybar
for mon in $(bspc query -M --names); do
    MONITOR=$mon polybar -r main &
done

if [ "$1" = 0 ]; then
    nm-applet &
    ~/.config/bspwm/organize
fi

bspc config border_width 2
bspc config window_gap   8

bspc config focused_border_color "#00AAFF"
bspc config normal_border_color  "#444444"

bspc config borderless_monocle false
bspc config gapless_monocle    true

bspc config pointer_modifier mod4
bspc config pointer_action1  move
bspc config pointer_action2  none
bspc config pointer_action3  resize_corner

bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer   true
bspc config pointer_motion_interval 50
bspc config single_monocle          false

bspc config automatic_scheme alternate
bspc config remove_unplugged_monitors true

bspc rule -r '*'
bspc rule -a Emacs state=tiled
bspc rule -a feh state=floating
bspc rule -a Spotify desktop=Music

~/.fehbg
