#!/bin/sh

pkill sxhkd
sxhkd &

bspc monitor -d 1 2 3

bspc config border_width        2
bspc config window_gap          10

bspc config focused_border_color "#00AAFF"

bspc config borderless_monocle  false
bspc config gapless_monocle     true

bspc config pointer_modifier    mod4
bspc config pointer_action1     move
bspc config pointer_action2     none
bspc config pointer_action3     resize_corner

bspc config pointer_follows_focus   false 
bspc config pointer_follows_monitor false
bspc config focus_follows_pointer   true
bspc config pointer_motion_interval 100


~/.fehbg
~/.config/polybar/launch.sh bspwm